"""Fix groups relations

Revision ID: 62ddb877ff86
Revises: b45d9c4165b5
Create Date: 2024-07-11 15:34:54.424681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62ddb877ff86'
down_revision: Union[str, None] = 'b45d9c4165b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_title_zoo_id', 'group', ['title', 'zoo_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_title_zoo_id', table_name='group')
    # ### end Alembic commands ###
