"""remove kind field

Revision ID: ea76320a6c5f
Revises: d963dc634848
Create Date: 2024-07-13 12:47:22.733829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea76320a6c5f'
down_revision: Union[str, None] = 'd963dc634848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'kind')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
