"""Fix groups relations

Revision ID: f141b45db52a
Revises: 1baec5cfc5d3
Create Date: 2024-07-11 18:48:17.338818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f141b45db52a'
down_revision: Union[str, None] = '1baec5cfc5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_name_zoo_id_group_id', 'event_type', ['name', 'zoo_id', 'group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_name_zoo_id_group_id', table_name='event_type')
    # ### end Alembic commands ###
